---
dependencies:
  - role: gantsign.visual-studio-code
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions:
          - streetsidesoftware.code-spell-checker
          - ms-python.python
