---
- name: Setup workstation
  hosts: localhost
  connection: local
  roles:
   - common
#    - desktop
  tasks:
    - git_config:
        name: remote.origin.url
        repo: "{{ ansible_env.HOME }}/.local/share/chezmoi"
        scope: local
        value: git@github.com:AaronNBrock/dotfiles.git
#    - include: tasks/packages.yml
