---
- name: Setup workstation
  hosts: localhost
  connection: local
  roles:
    - common
    - desktop
  tasks:
    - debug:
        msg: "{{ (item|basename()|splitext)[0] }}"
      with_items:
      - 'https://github.com/zsh-users/zsh-autosuggestions.git'
      - 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
#    - include: tasks/packages.yml
